services:
  jwd.i18n.event.adapter:
    class:     Janwebdev\SFI18nBundle\Mapping\Event\Adapter\ORM\DoctrineAdapter
  jwd.i18n.locale:
      class:     Janwebdev\SFI18nBundle\Locale\Locale
      arguments: [%locale%]    
  jwd.i18n.locale_listener:
      class:     Janwebdev\SFI18nBundle\Listener\LocaleListener
      arguments: ["@jwd.i18n.locale"]
      tags:
          - { name: kernel.event_subscriber }
  jwd.i18n.translatable_listener:
      class:     Janwebdev\SFI18nBundle\Listener\TranslatableListener
      arguments: ["@jwd.i18n.event.adapter", "@jwd.i18n.locale"]
      tags:
          - { name: doctrine.event_subscriber }